### ISSUE TITLE
Creating DNS records for pods

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#126]
There's a new feature in an upcoming version of FDB to use DNS names instead of IP addresses in the cluster file. I think this will significantly improve the reliability of running FDB on Kubernetes, where updating pods causes them to get a new IP address. To prepare for using this feature, we should configure our pods so they get DNS entries within the Kubernetes cluster. I think we can do this by having a headless service for every pod.

**Comment by rbtcollins** [comment]
headless services per pod is an awkward, but possible way. Deployments also create DNS records; I suggest looking into how Deployments and Daemonsets create DNS records for pods, and following suit, rather than creating a plethora of services.

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields

So I think you'd have the cluster object act as the namespace here: `$pod.$fdbcluster.$namespace.svc.$k8scluster.example.org.`

A *single* headless service will actually create DNS records for all the pods, if correctly configured,:
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields

`$pod.$subdomain.$namespace.svc.$k8scluster.example.com.`

For the multi-k8s cluster case, endpoint replication will be needed, I suggest not getting involved in that and instead pointing users at things like this (hi @akshaychitneni :P) https://github.com/vmware/k8s-endpoints-sync-controller

**Comment by rbtcollins** [comment]
Oh, and a further comment - the cluster service ip range is quite limited in most clusters - it scales, but explicitly orders of magnitude less than pod ips; I worry that large clusters will put unexpected stress on the allocation there.

**Comment by brownleej** [comment]
If we're using headless services, will there be any limitation based on the cluster service IP range?

**Comment by brownleej** [comment]
Thanks for the suggestion about using a single headless service! That seems to work well for this use case, and it'll help decouple this work from some other potential use cases for per-pod services.

**Comment by rbtcollins** [comment]
> If we're using headless services, will there be any limitation based on the cluster service IP range?

I think not, but I'll need to check; certainly there will be more footprint on the service controller as it has to watch (say) 120 different sets of pods, if we are doing this for all 120 pods in a scaled cluster.
That said, there's no point really having a separate headless service per pod, as noted above; a headed service per pod is the point where a static IP could be emulated on a per-pod basis, but the concerns above about scalablity apply.
