### ISSUE TITLE
Tester process count results in unhealthy test processes of the Foundationdb

### ISSUE THREAD

**Issue by iyuroch** [FoundationDB/fdb-kubernetes-operator#1346]
### What happened?

Applying foundationdbcluster with:

`
processCounts:
  tester: 4
`
result in unhealthy tester nodes in foundationdb cluster.

### What did you expect to happen?

Have test processes in foundationdb

### How can we reproduce it (as minimally and precisely as possible)?

Add processCounts with tester blocks

### Anything else we need to know?

Changing class in fdbmonitor configuration from tester to test resolves the issue

### FDB Kubernetes operator

0.51.1

### Kubernetes version

1.22

### Cloud provider

AWS

**Comment by iyuroch** [comment]
@johscheuer I'm thinking if we should change definition of process name from Tester to Test or to add this in chunk of fdbmonitor.conf - what do you think would be preferable approach? Short term changing fdbmonitor generation, do you see any issues with changing tester -> test, do we have to take something in consideration with that change?

**Comment by johscheuer** [comment]
Changing the name from `tester` to `test` make sense to me. To be more precise with the deprecation policies we have to desecrate `tester` and refer to the newly added `test`.

**Comment by iyuroch** [comment]
@johscheuer does it mean that we will not backport this to older CRD's having bug? Maybe we can have combined approach - add implicit rename of class in fdbmonitor generation from "tester" -> "test" and have deprecation policy for CRD?

**Comment by johscheuer** [comment]
We have a few examples in our code for how we do the deprecations: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/api/v1beta2/foundationdbcluster_types.go#L1669-L1673.We don't maintain the v0 operator release and the best path forward is to upgrade the CRD and the operator to the latest version (there were quite a few bug fixes since then). If you want to make changes to the v0 version of the operator you have to base your changes on the v0 branch.

**Comment by iyuroch** [comment]
@johscheuer I've added this -> https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1362
Let me know how to proceed from this point.

**Comment by johscheuer** [comment]
Fixed in the PR above. Thanks again!
