### ISSUE TITLE
Host helm chart into a repository

### ISSUE THREAD

**Issue by viveksinghggits** [FoundationDB/fdb-kubernetes-operator#163]
Now that we have the helm chart, after [this PR](https://github.com/FoundationDB/fdb-kubernetes-operator/pull/59), we should now host that helm chart so that the controller can be installed using helm.
We can use github pages to helm chart.

ref: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/59#issuecomment-592434661

This might help host the chart
https://github.com/helm/chart-releaser

**Comment by brownleej** [comment]
Do we have examples of other operators following this pattern?

**Comment by viveksinghggits** [comment]
Hey @brownleej,
[This document](https://helm.sh/docs/topics/chart_repository/) has an example under `GitHub Pages example` section.

**Comment by brownleej** [comment]
That's an example from Helm. I was looking for an example of another operator in real usage following this pattern.

**Comment by viveksinghggits** [comment]
Got you, let me see if I can find something out.

**Comment by johscheuer** [comment]
Since https://github.com/helm/charts is not maintained anymore it seems like https://artifacthub.io is the right place + https://operatorhub.io. I think it makes sense to publish the operator on these platforms to make it easier for people to find the operator.

**Comment by protosam** [comment]
There is no "right" place persay, because the landscape is such that people are strung across different ways of consuming operators.

The chart releaser is nice. Kubernetes-sigs uses the [github action here](https://github.com/helm/chart-releaser-action) to produce both [nfs-subdir-external-provisioner](https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/) and [nfs-ganesha-server-and-external-provisioner](https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/).

The work is pretty much just [this](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/.github/workflows/helm-chart-release.yml). Seems like low hanging fruit to accomplish.
