### ISSUE TITLE
Operator requires node access

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#1727]
### What happened?

For the taint feature we added a field indexer to access nodes quickly based on their node name:

```go
	err = mgr.GetFieldIndexer().IndexField(context.Background(), &corev1.Node{}, "metadata.name", func(o client.Object) []string {
		return []string{o.(*corev1.Node).Name}
	})
	if err != nil {
		return err
	}
```

This has the side effect, that the operator service account requires the RBAC setup to list nodes. We should add a command line flag to make this optional.

### What did you expect to happen?

The operator should start without needing node list access.

### How can we reproduce it (as minimally and precisely as possible)?

Create an operator deployment without node list access.

### FDB Kubernetes operator

<details>

```console
$ kubectl fdb version
# paste output here
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

**Comment by manfontan** [comment]
I believe this bug will hit anyone using the deployment config sample 
https://github.com/FoundationDB/fdb-kubernetes-operator/blob/b0969838b2b214632ef0283ce263a62936fc3235/config/samples/deployment.yaml#L123

Since the sample uses a RoleBinding instead of a ClusterRoleBinding the node list permissions won't work. Probably ClusterRoleBinding to all the resources is to permissive. Maybe using a ClusterRole for node permissions and Role for namespace resources would be a better approach here?
