### ISSUE TITLE
Large excludes fail due to 10% estimate

### ISSUE THREAD

**Issue by rbtcollins** [FoundationDB/fdb-kubernetes-operator#272]
We had a cluster that had become massively over-sized (#268). Trying to down-size this, the exclude call was failing, but not with the normal timeout due to data-moving issue.

Reproducing it directly in fdbcli I could see that it was because it was estimating that we would run out of disk space. (Narrator: We were not going to run out of disk space). I applied the exclude with force, waited for it to apply and eventually everything worked.

There were a couple of contributing factors here I think; one is - I speculate - that the 10% buffer is calculated on the current available storage, not the end storage. And we definitely are going to be under that when shrinking in one step down to 25% of the current disk. The other is that having just sized up the cluster hadn't stabilised - disk estimates and footprint shrunk once things had time to quiet down.

I'm not entirely sure what to do with this one; perhaps detect it and try shrinking in smaller steps, on the basis that the user probably knows what they want, and the system may just be being overly cautious. Possibly treat this as a FDB bug.

**Comment by brownleej** [comment]
The exclusion safety in FDB can definitely throw false positives, since it's designed to be conservative and avoid any unsafe exclusions as a first priority. The basic assumption is that the disk space usage on every remaining process will grow by a factor of `currentServers/remainingServers`. This is a pessimistic estimate in the case where data is unevenly distributed across the remaining processes, since the data distribution will try to take that into account. It can also be a problem if your storage servers do not have exclusive use of their disk, since the used space is based on the disk's used space rather than the files in the process's data directory.

We've never implemented a force exclude command in the operator, since that will likely require human judgment, risk assessment, and knowledge of how the disks are laid out. It should be the case that once you initiate a force exclude manually the operator will be able to continue running normally. This is also a place where we could improve the visibility of these errors so that the user can distinguish this from the case where the exclusion is in-progress and know that they need to consider a force exclude.

**Comment by JoshuaMcManus** [comment]
Old issue - closing as not to be fixed.
