### ISSUE TITLE
operator sometimes numbers pods starting from 2

### ISSUE THREAD

**Issue by kcking** [FoundationDB/fdb-kubernetes-operator#332]
We currently have a cluster with 4 log processes and 3 storage processes. On our prod environment we have pods named
```
documents-log-1
documents-log-2
documents-log-3
documents-log-4
documents-storage-1
documents-storage-2
documents-storage-3
```

whereas on staging we ended up with
```
documents-log-2
documents-log-3
documents-log-4
documents-log-5
documents-storage-1
documents-storage-2
documents-storage-3
```

Is this expected behavior, or is there some way to make sure the numbering is deterministic? We are productionizing some disaster recovery tools and it would simplify them if we could rely on pod names

**Comment by brownleej** [comment]
Yes, this is expected in some cases. When the operator replaces instances, it creates new pods before shutting down old pods, in order to avoid any loss of fault tolerance during the data migration. Similarly, if you grow and then shrink a cluster, it is not guaranteed to remove the highest-numbered pods, as doing so may result in sub-optimal distribution of processes across fault domains.

The operator always starts creating pods from 1, though. I've seen cases where it creates too many pods in cluster creation, and then removes them to get to the desired process count. I would guess that is what happened in your case. This behavior isn't desired, but it should be harmless.

In terms of disaster recovering tooling, I would recommend looking at the active list of pods or instances in the cluster. Depending on what your tooling is trying to do with the pod names, though, there may be accommodations we can build.

**Comment by kcking** [comment]
Thanks for the detailed answer! This indeed might be from a storageclass migration we did on staging.

I am setting up performant snapshot backup, and thought it would make the restore process easier if I could just recreate the pvcs with the same numbering so that upon creating a new `foundationdbcluster` k8s resource, the pods would find their volumes implicitly. 

It sounds like new clusters should always start their numbering from 1, so I suppose I could just "renumber" the snapshots when creating pvcs from them.
