### ISSUE TITLE
Performant backup recovery strategy

### ISSUE THREAD

**Issue by kcking** [FoundationDB/fdb-kubernetes-operator#340]
We are looking to use fdb performant backup (as documented [here](https://github.com/apple/foundationdb/blob/master/documentation/sphinx/source/disk-snapshot-backup.rst)). Since we're using AWS EBS volumes with native snapshot capabilities, this method is more natural for us compared to an S3/blob storage backup strategy.

I have our cluster set up to take snapshots using the `fdbcli` `snapshot` command, and am now figuring out how to restore an oeprator-managed cluster using these snapshots.

My first strategy was
1. pre-create the `pvc`s that have snapshots and back them with the corresponding snapshot content as described [here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#create-persistent-volume-claim-from-volume-snapshot)
1. bring up the new fdb cluster
1. set the owner of the pre-created `pvc`s to the cluster `uid`
1. manually set the connectionString to the three pods that have coordinator data in their snapshots

However this falls apart at step 3. as the expected `pvc` spec hash does not match and this check fails https://github.com/FoundationDB/fdb-kubernetes-operator/blob/1e1fd2b47200b5d5b7b46c8b0d068cc8fdf4eb0a/controllers/replace_misconfigured_pods.go#L77

It seems that this results in the `fdbmonitor.conf` file never being populated for the pods that have `pvc`s backed by snapshots.

I'm going to continue looking into how to get this working with the operator (perhaps a relaxation of a couple of checks if there is a `restoreFromSnapshot` flag set might work), but just want to reach out and see if there is any current work going on to support this/if you had any better ideas for how to get this working.

Thanks!

**Comment by brownleej** [comment]
Yeah, this is something we could try to add first-class support for in the operator. In the shorter-term, I would think that you could manually set the annotation when you create the PVC in step 1. It's a hash of the JSON representation of the spec the operator uses to create the PVC. I imagine you could re-create the hash yourself based on the spec you're using to create the PVCs.

It's possible that with the feature in #309, you could make this work without the annotations, by prepopulating the cluster with the old connection string and instance list. It's hard to say since the feature isn't implemented yet, and is targeting a slightly different problem, but it seems to have some overlap.

**Comment by kcking** [comment]
Ah good point on the workaround. I think what I'll do is record the spec hash when we take snapshots, that way I don't have to bring golang's json encoder to the party.

I deployed a fork of the operator with only the single change to ignore pvc hash on that line mentioned above, and my restore procedure worked. I'd be happy to work with you on bringing better operator support for it.

One tricky thing was that in this scenario I was restoring to a new fdbcluster, but alongside the old cluster. The nodes came online with a snapshotted `fdb.cluster` file, which connected them to the old cluster and caused cluster unavailability. We're solving this by using calico + networkpolicy to prevent pods from different clusters from communicating. Once the nodes are online, I have a separate procedure to update the connection string to the nodes that have the coordinator data in their snapshots.
