### ISSUE TITLE
Support for continuous backup

### ISSUE THREAD

**Issue by dulguun-cognite** [FoundationDB/fdb-kubernetes-operator#347]
`fdbbackup` command-line tool supports a continuous backup by running it with an argument `-z`. https://apple.github.io/foundationdb/backups.html#fdbbackup-command-line-tool
> Perform the backup continuously rather than terminating once a restorable backup is achieved. Database mutations within the backup’s target key ranges will be continuously written to the backup as well as repeated inconsistent snapshots at the configured snapshot rate.

Is there support to run the cluster with continuous running backup?

**Comment by brownleej** [comment]
There is limited support for this in the operator today, through the FoundationDBBackup resource. There is an ongoing project to fill out the support for backups, which is why the backup support is not fully documented yet. We're tracking the issues for this under the [Backup Management](https://github.com/FoundationDB/fdb-kubernetes-operator/projects/2) project.

**Comment by JoshuaMcManus** [comment]
Old issue - closing as not to be fixed.
