### ISSUE TITLE
Provide a way to install the operator in non default namespaces

### ISSUE THREAD

**Issue by viveksinghggits** [FoundationDB/fdb-kubernetes-operator#55]
I think as of now, the operator can only in installed on default namespace which happens by default if we follow the README, we should have a way to install the cluster in the non default namespaces well.

Even if we deploy the operator in the default namespace and try to deploy local_cluster.yaml in another namespace the fdb cluster pod dont get into running state because there are some secrets that are required to fdb cluster to get the pods running.

**Comment by brownleej** [comment]
The examples in the repo right now are intended for a local testing environment. In PR #47 there are some additional examples which should be more namespace-agnostic. There are still namespaces in them, which we should probably remove.

In general, we should improve the documentation to make clear the limitations of the examples we're including. Most of them are only designed for helping with local development of the operator. If you're running in a real environment, and you want to enable TLS, you will need a different, and more secure, mechanism for providing certificates. We can't give much guidance on this, since it depends heavily on the environment you're running in.

**Comment by brownleej** [comment]
I've removed the namespaces from the examples I mentioned before, and merged those updates to the README. @viveksinghggits Does that address what you were looking for?

**Comment by viveksinghggits** [comment]
Hi @brownleej  
I think yes, but can you look at https://github.com/FoundationDB/fdb-kubernetes-operator/pull/59
that will solve a lot for problem for anyone who is trying to deploy the operator on k8s cluster.
