### ISSUE TITLE
Skipping instances to be removed when generating the initial cluster file

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#577]
If we have an instance that fails to come up when we first create a cluster, we may want to spin up a new instance to replace it. This causes problems with the step to generate the initial cluster file, because it requires that all processes have IPs assigned. I think we should ignore instances that are marked for removal when generating the initial cluster file.

**Comment by johscheuer** [comment]
Looking at the code I think we already solved that.

**Comment by brownleej** [comment]
Can you clarify what part of the code is handling this case?

**Comment by johscheuer** [comment]
You are right the issue is not solved, we have to change the for loop here: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/controllers/generate_initial_cluster_file.go#L77-L88, in addition we might want to filter the Pods (https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/controllers/generate_initial_cluster_file.go#L47-L50) by the running status. I was mistaken by the [checkCoordinatorValidity](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/b97e85a59dc859a60eede96340dc305031cbc8f3/controllers/cluster_controller.go#L577) where we added some additional checks to prevent this scenario.
