### ISSUE TITLE
Can I speed up the initial reconciliation of my cluster?

### ISSUE THREAD

**Issue by funkypenguin** [FoundationDB/fdb-kubernetes-operator#628]
Hey guys!

Quick question - we're using fdb-operator in a CI enviroment which requires us to startup and destroy entire namespaces with every commit pushed through the pipeline. Our services depend on a reconciled fdb-cluster, which seems to take ~3 minutes from when the cluster resource is first applied to Kubernetes. Consequently, I end up with all my _other_ pods crashlooping for ~3min (sometimes more, because of backoffs) until the FDB cluster is reconciled.

Is there a "knob" I can tune to make this initial reconciliation happen any faster?

Thanks!
D

**Comment by johscheuer** [comment]
Currently we don't have a knob to make it faster (otherwise we just would make the reconciliation always faster) one way is to add an annotation every few seconds to trigger a reconciliation we do that in our e2e test (https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/e2e/cluster_test.go#L170-L185). There are a number of places where we expect to get a faster reconciliation once we changed the way how these things work.

**Comment by brownleej** [comment]
I think a large section of the delay in initial reconciliation is the feedback loop with pod IP addresses. We currently launch the initial pods, wait for them to be assigned an IP, create the initial cluster file, and updates the pods to have that cluster file. That last update step gets blocked on the config map propagation, which isn't a very fast process. It's possible that we could speed this up for cases where we are using IPs from services rather than pods, since we could generate the cluster file before creating pods. That kind of approach would also be useful if we are use DNS names rather than IPs in the cluster file at some point in the future.

**Comment by johscheuer** [comment]
The last time I looked into this the ConfigMap sync can take up to 1-2 min (for a kind/docker-desktop) cluster. So even if we would speed up the initial reconciliation phase (which is a good idea) we still have the limitation of the ConfigMap propagation. I already thought about giving the sidecar the ability to watch the ConfigMap but I'm not sure if we want to have x Pods watching the ConfigMap.

**Comment by johscheuer** [comment]
We added some changes to the code that should speed up the cluster creation: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/734 if you still see an issue with a cluster taking long to spin up please reopen the issue.
