### ISSUE TITLE
Add support for image digests. 

### ISSUE THREAD

**Issue by jackson-chris** [FoundationDB/fdb-kubernetes-operator#670]
The operator seems to not currently support image digests. It is common on openshift to take advantage of [mirror registries](https://docs.openshift.com/container-platform/4.2/installing/install_config/installing-restricted-networks-preparations.html#installation-about-mirror-registry_installing-restricted-networks-preparations) to pull images which requires referencing images by their digests instead of tags. 

This is a request to alter the operator to be able to support digests instead of tags.

**Comment by johscheuer** [comment]
The current solution would be to set `allowTagOverride` in the [processSettings](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/cluster_spec.md#processsettings) and then you can define your image with the tag. A rough example how that could look like can be found in the samples folder: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/config/samples/cluster_local.yaml#L18. We already have an issue to keep track of that problem and hopefully we can close that work in the future: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/387#issuecomment-812753652 or if you have interest in this feature PRs are welcome :)

**Comment by johscheuer** [comment]
I think with the [image config](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/cluster_spec.md#imageconfig) that should be supported. If you still see any issues please reopen this issue.

**Comment by brownleej** [comment]
@johscheuer I tried using an image digest in some recent tests, and the syntax for them is slightly different in a way that the image configs don't support.

**Comment by johscheuer** [comment]
I think adding support for this should be pretty straightforward with the `ImageConfig` by just adding an additional field `Digest`. @blindenvy if you have some capacity and need this feature I'm happy to review those changes. I think the digest should have the highest "priority" if specified because that's the most precise way to define which image should be running. The. required changes are needed here: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/api/v1beta1/foundationdbcluster_types.go#L2294-L2345 but I would suggest to wait until the v1bea2 CRD is merged and add the functionality there.

**Comment by blindenvy** [comment]
I'm quite overloaded atm, but I will see if I can find some time to work on this. Thanks for the guidance on where to start.
