### ISSUE TITLE
Feature request: send logs to stdout for kubernetes consumption

### ISSUE THREAD

**Issue by funkypenguin** [FoundationDB/fdb-kubernetes-operator#810]
Hey guys!

Would it be possible to configure the fdb pods (_spawned by the operator_) to output logs to stdout, as well as to the filesystem? For us, this'd mean we could capture the log output in our logging platform (_graylog / loki_), rather than having to look in the pod's filesystem to find the logs :)

Cheers!
D

**Comment by johscheuer** [comment]
Since FoundationDB itself doesn't support to log to stdout/stderr (or both) see https://apple.github.io/foundationdb/configuration.html#foundationdb-conf there is nothing that the operator could configure. One way to workaround this is by adding an additional sidecar that streams (e.g. tail) the logs to stdout, that would be part of the [ProcessSettings](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/cluster_spec.md#processsettings).

**Comment by johscheuer** [comment]
Closing this one. The workaround for this is just running a sidecar with a tail command.
