### ISSUE TITLE
Allow the sidecar to read labels from nodes

### ISSUE THREAD

**Issue by johscheuer** [FoundationDB/fdb-kubernetes-operator#817]
For more flexibility we should allow the sidecar to read labels from their Kubernetes node. This makes the process of using labels from the underlying Kubernetes node easier and doesn't require any additional information. This option should be optional for environments where the user is not able to read nodes.

**Comment by brownleej** [comment]
Is this is referring to the fault domain labels we use as substitutions in the locality fields?

**Comment by johscheuer** [comment]
Right, the idea would be to allow to read the value of labels like `topology.kubernetes.io/zone` or `topology.kubernetes.io/region` defined in the [Kubernetes docs](https://kubernetes.io/docs/reference/labels-annotations-taints). I wouldn't limit the labels to the well defined ones but rather have a generic approach to get the information from a node to also support custom node labels.

**Comment by brownleej** [comment]
@johscheuer I think it would make sense to implement this in the new sidecar, since it already has a Kubernetes client as a requirement, and to implement this before we publish images with the new sidecar. That should allow us to make it a requirement for using the new locality structure in your three_data_hall design, and make it easy for people to adopt without needing to use specific versions. Do you think that approach makes sense?

**Comment by johscheuer** [comment]
That makes sense 👍 Do you think we should close this issue or just relabel it for the new sidecar image?

**Comment by brownleej** [comment]
Let's relabel it.

**Comment by gm42** [comment]
On this topic: I managed to inject that information (zone) by using the `ADDITIONAL_ENV_FILE` (was around the time I made [this PR](https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1980))
