### ISSUE TITLE
Running clusters with IPv6

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#85]
Kubernetes has dual-stack IPv4/IPv6 support in alpha now. When running a cluster on that configuration, users will want to control whether their cluster is running on IPv4 or IPv6. We should have an option for this, and a mechanism to transition between IPv4 and IPv6. The transition mechanism can follow the pattern we use for enabling and disabling TLS.

**Comment by brownleej** [comment]
I think we should explore using migration as a transition mechanism instead, to simplify the initial work.

**Comment by johscheuer** [comment]
I'm not sure if migration is there really helpful since all Pods will have an IPv4 and IPv6 address in Dual-Stack we only have to change the [Service config](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#dual-stack-service-configuration-scenarios) if we use Services. Otherwise it's just `IPv4 -> IPv4/IPv6 -> IPv6` if we want to move from IPv4 to IPv6 otherwise we have to execute these step in the reverse order. We also might want to support Dual-Stack clusters?

**Comment by brownleej** [comment]
I'm going to close this with the linked PR, and follow additional issues for more nuanced aspects of IPv6 support.
