### ISSUE TITLE
Expected operator memory usage > 256Mi?

### ISSUE THREAD

**Issue by funkypenguin** [FoundationDB/fdb-kubernetes-operator#854]
Hey guys!

I had my fdb-operator pod limited to 256Mi RAM, and recently (_for the first time I can recall_), it was OOMKilled, trying to use >350Mi.

Is this expected, or a bug? If it's expected, have you got a feeling for how much RAM to allocate per-cluster (_our Kubernetes cluster had about 10 FDB clusters running at the time, each in their own namespace_)

Thanks!
D

**Comment by johscheuer** [comment]
Hi,

this is an expected behaviour and we currently don't have any recommendations (we are working on this). The memory requirements depend on different things:

- How many clusters are managed by the operator
- How large are these clusters
- Some additional capacity is needed for FDB clusters that span across multiple Kubernetes clusters

In the end the controller-runtime will cache the FDB custom resource and al related resources like Pods, PVC, Services etc. in addition to that we require some capacity during the reconcile loop e.g. when we fetch the cluster status from FDB or when we iterate over some components. 

Once we have an answer we will document the requirements.

**Comment by johscheuer** [comment]
I'm going to close this stale issue. Feel free to reopen it.
