### ISSUE TITLE
FDB operator unable to recover after OCP/K8S cluster restart

### ISSUE THREAD

**Issue by blindenvy** [FoundationDB/fdb-kubernetes-operator#928]
We were doing some fault testing and restarted our OCP cluster and observed that on cluster restart the coordinator pods all had new IP addresses yet the operator is unable to recover on its own to update the coordinator ips in the fdb cluster file. We then discovered the following documentation: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/manual/debugging.md#coordinators-getting-new-ips which explains how to correct this problem. 

Can someone explain why this corrective action cannot be build into the operator itself?

**Comment by johscheuer** [comment]
Hi, this is a well known issue: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/manual/warnings.md#risks-when-ips-change one way to prevent this is to use `services` in front of the FDB Pods. Did you try to run this command and did it recover the cluster state? 

I think we decided to move this into the plugin since this was a rather new action we added recently and we wanted to reduce the risk of adding new functionality in the operator. Second we think/thought that this is rather an uncommon action since this requires that you either restart all your Pods (or a majority of coordinator Pods) otherwise the operator will handle an unreachable coordinator correctly and will change it to a new one.

@brownleej maybe has some more insights why we put this into the plugin and not the operator.

**Comment by blindenvy** [comment]
> Did you try to run this command and did it recover the cluster state?

Yes we ran the command and it did indeed resolve the issue. From our perspective it would be better if manual intervention would not be required. 

> Second we think/thought that this is rather an uncommon action since this requires that you either restart all your Pods (or a majority of coordinator Pods) otherwise the operator will handle an unreachable coordinator correctly and will change it to a new one.

This issue occurred when we restarted all the nodes of the Openshift (OCP) cluster, it seems a common use case from our customers where they are powering down their clusters completely (say over the weekend) to avoid infrastructure cost.

**Comment by johscheuer** [comment]
Sorry for the delay. If that's a use case for you feel free to add this behaviour to the operator and open a PR with the changes. From our side this is currently not a high priority.

**Comment by brownleej** [comment]
Our current plan to avoid manual intervention in this case is to get support in FoundationDB for DNS names in the cluster file, and then transition to using that strategy in the operator. The fix for this in the plugin involves running commands directly in the context of other containers, which is not an interaction model we have in the operator yet, so we didn't want to jump to fully automating it at first without more experience.

**Comment by johscheuer** [comment]
Closing, since this is a known issue with a workaround. Either using services or DNS (in the future) will prevent this.
